### ISSUE TITLE
Code blok skrytý v <ksi-tip> rozbije formátovanie

### ISSUE THREAD

**Issue by hadamove** [fi-naskoc/web-frontend-angular#8]
Reprodukcia

1. V úlohe vytvorím \<ksi-tip> blok
2. Do tela tohto bloku pridám code blok (\``` ... \```)

Očakávané správanie:
code blok vyzerá rovnako ako keď nie je vnorený v \<ksi-tip> bloku

Reálne správanie:
code blok má rozbité formátovanie (viz. obrázok):

<img width="1428" alt="Screenshot 2023-08-27 at 16 36 16" src="https://github.com/fi-naskoc/web-frontend-angular/assets/55924102/94162c3e-ae80-4a9b-9541-ab3670b6235f">

Browser: Firefox, Safari, Chrome

Poznatky:
Vyzerá to, že sa nejakým spôsobom pobije CSS \<ksi-tip> bloku a code bloku. Dirty fix je pridať k atribútom `!important`:
<img width="1428" alt="Screenshot 2023-08-27 at 16 36 29" src="https://github.com/fi-naskoc/web-frontend-angular/assets/55924102/d1469ba4-7349-4b7b-939c-fbc6c14ab7c7">

**Comment by hadamove** [comment]
Vyzerá to, že to podobne rozbíja aj tabuľky. Myslíš, že by sa to dalo opraviť spolu?

<img width="1081" alt="Screenshot 2023-08-28 at 11 42 40" src="https://github.com/fi-naskoc/web-frontend-angular/assets/55924102/3474d8c6-0490-4d2f-99e2-cfb78b90b49c">

<img width="1081" alt="Screenshot 2023-08-28 at 11 42 37" src="https://github.com/fi-naskoc/web-frontend-angular/assets/55924102/59735407-415e-4d56-bef6-1cb8a98b7b8c">

**Comment by esoadamo** [comment]
Díky za podrobný report! Provedl jsem super-hard fix https://github.com/fi-naskoc/web-frontend-angular/commit/a780962546cdfa12e6b2153d32a1389c7eb01450

@hadamove už můžeš případně oddělat `! important` ze své úlohy
